# Generated by Django 3.2.6 on 2021-08-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks2', '0003_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='credentials',
            new_name='email',
        ),
    ]
