# Generated by Django 3.2.6 on 2021-08-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks2', '0004_rename_credentials_credentials_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='password',
            field=models.CharField(default='password', max_length=36),
            preserve_default=False,
        ),
    ]
