# Generated by Django 3.2.6 on 2021-08-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks2', '0005_credentials_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet',
            new_name='balance',
        ),
    ]
