# Generated by Django 3.2.6 on 2021-08-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks2', '0006_rename_wallet_wallet_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credentials',
            new_name='Credential',
        ),
    ]
