# Generated by Django 3.2.6 on 2021-08-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks2', '0007_rename_credentials_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=12),
        ),
    ]
